Repository woowa-techcamp-2022/android-repo-08, pull requests merged in 2022-07, with the labels that each got.

#2 네트워크 모듈 구현 #1
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/reposearchapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/reposearchapp/data/Result.kt
  app/src/main/java/com/example/reposearchapp/data/remote/RepoApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/RepoService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/User.kt
  app/src/main/java/com/example/reposearchapp/presentation/MainActivity.kt
  app/src/main/java/com/example/reposearchapp/presentation/base/BaseFragment.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/reposearchapp/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: feature

#9 로그인 구현 #6
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/reposearchapp/RepoSearchApp.kt
  app/src/main/java/com/example/reposearchapp/data/Result.kt
  app/src/main/java/com/example/reposearchapp/data/entity/AccessTokenRequest.kt
  app/src/main/java/com/example/reposearchapp/data/entity/AccessTokenResponse.kt
  app/src/main/java/com/example/reposearchapp/data/remote/AccessApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/AccessService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/RepoApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/User.kt
  app/src/main/java/com/example/reposearchapp/data/repository/AccessTokenRepository.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/presentation/MainActivity.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainActivity.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainViewModel.kt
  app/src/main/java/com/example/reposearchapp/util/Event.kt
  app/src/main/res/drawable/background_button_large.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature

#17 저장소 검색 기능 구현 #11
  app/build.gradle
  app/src/main/assets/githubLanguageColor.json
  app/src/main/java/com/example/reposearchapp/data/RepoItemModel.kt
  app/src/main/java/com/example/reposearchapp/data/Token.kt
  app/src/main/java/com/example/reposearchapp/data/entity/Item.kt
  app/src/main/java/com/example/reposearchapp/data/entity/Owner.kt
  app/src/main/java/com/example/reposearchapp/data/entity/RepoResponse.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubService.kt
  app/src/main/java/com/example/reposearchapp/data/repository/AccessTokenRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/SearchRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/issue/DefaultIssueRepository.kt
  app/src/main/java/com/example/reposearchapp/di/CoroutinesModule.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/di/ProvideAPI.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/RepoAdapter.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/RepoViewHolder.kt
  app/src/main/java/com/example/reposearchapp/presentation/custom/CustomSearchView.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainActivity.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainViewModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/reposearchapp/util/BindingAdapters.kt
  app/src/main/java/com/example/reposearchapp/util/Event.kt
  app/src/main/java/com/example/reposearchapp/util/GithubLanguageColorUtil.kt
  app/src/main/java/com/example/reposearchapp/util/KeyboardUtil.kt
  app/src/main/java/com/example/reposearchapp/util/Utils.kt
  app/src/main/res/drawable/background_search_pressed.xml
  app/src/main/res/drawable/background_search_unpressed.xml
  app/src/main/res/drawable/circle.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_repo.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature🔥, 박해민🌹

#34 쉐어드 프리퍼런스로 수정, 네트워크 모듈 di 적용 #16
  app/build.gradle
  app/src/main/java/com/example/reposearchapp/data/Token.kt
  app/src/main/java/com/example/reposearchapp/data/remote/AccessService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubServiceInterceptor.kt
  app/src/main/java/com/example/reposearchapp/data/repository/AccessTokenRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/SearchRepository.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/di/NetworkModule.kt
  app/src/main/java/com/example/reposearchapp/di/ProvideAPI.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainActivity.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainViewModel.kt
  build.gradle
  gradle.properties
Labels: enhancement, feature🔥

#36 서치 화면 툴바 구현 #26
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchFragment.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_searchname.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feature🔥

#30 Notification 리스트 아이템 Swipe Delete 기능 구현
  app/src/main/java/com/example/reposearchapp/data/entity/issue/Issue.kt
  app/src/main/java/com/example/reposearchapp/data/entity/notification/Notification.kt
  app/src/main/java/com/example/reposearchapp/data/entity/notification/read/NotificationReadResponse.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GitApiService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/repository/notification/DefaultNotificationRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/notification/NotificationRepository.kt
  app/src/main/java/com/example/reposearchapp/model/notification/NotificationModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/notification/NotificationItemSwipeHelper.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationState.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationViewModel.kt
  app/src/main/java/com/example/reposearchapp/util/StringExtension.kt
  app/src/main/res/values/strings.xml
Labels: feature🔥, 박해민🌹, Review Request🔥🔥

#33 Notification 댓글 개수 받아와서 화면에 보여주기
  app/src/main/java/com/example/reposearchapp/data/entity/notification/Notification.kt
  app/src/main/java/com/example/reposearchapp/data/entity/subject/Subject.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GitApiService.kt
  app/src/main/java/com/example/reposearchapp/data/repository/notification/DefaultNotificationRepository.kt
  app/src/main/java/com/example/reposearchapp/data/url/Url.kt
  app/src/main/java/com/example/reposearchapp/model/notification/NotificationModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/notification/NotificationViewHolder.kt
  app/src/main/res/drawable/background_comment_number.xml
  app/src/main/res/layout/item_notification.xml
Labels: feature🔥, 박해민🌹, Review Request🔥🔥

#35 Home화면에서 Fragment 구조 변경하기
  app/src/main/java/com/example/reposearchapp/presentation/adapter/home/HomeViewPagerAdapter.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/issue/IssueFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 진연주🍿, UI⭐️, Review Request🔥🔥

#41 화면 회전에 따른 이슈 대응하기
  app/src/main/res/layout/fragment_home.xml
Labels: 진연주🍿, 박해민🌹, Review Request🔥🔥

#47 서치 화면 재진입시 초기화 #46
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchViewModel.kt
Labels: bug🐞

#45 이슈&알림 리스트에 swipe refresh 기능 추가
  app/build.gradle
  app/src/main/java/com/example/reposearchapp/di/ProvideAPI.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/issue/IssueFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationFragment.kt
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
Labels: feature🔥, 진연주🍿, 박해민🌹

#28 페이징 구현 #14
  app/build.gradle
  app/src/main/java/com/example/reposearchapp/data/SearchPagingSource.kt
  app/src/main/java/com/example/reposearchapp/data/entity/login/AccessTokenRequest.kt
  app/src/main/java/com/example/reposearchapp/data/entity/login/AccessTokenResponse.kt
  app/src/main/java/com/example/reposearchapp/data/entity/search/Item.kt
  app/src/main/java/com/example/reposearchapp/data/entity/search/Owner.kt
  app/src/main/java/com/example/reposearchapp/data/entity/search/RepoResponse.kt
  app/src/main/java/com/example/reposearchapp/data/remote/AccessApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubServiceInterceptor.kt
  app/src/main/java/com/example/reposearchapp/data/repository/SearchRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/login/AccessTokenRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/search/SearchRepository.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/di/NetworkModule.kt
  app/src/main/java/com/example/reposearchapp/model/search/RepoItemModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/search/RepoAdapter.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/search/RepoViewHolder.kt
  app/src/main/java/com/example/reposearchapp/presentation/login/LoginFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/main/MainViewModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_repo.xml
  build.gradle
Labels: feature🔥, 박해민🌹

#38 (페어) 프로필 구현 #37
  app/src/main/java/com/example/reposearchapp/data/entity/ProfileEntity.kt
  app/src/main/java/com/example/reposearchapp/data/entity/StarredByUserResponse.kt
  app/src/main/java/com/example/reposearchapp/data/entity/UserResponse.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/repository/ProfileRepository.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/model/profile/UserModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/profile/ProfileFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/profile/ProfileViewModel.kt
  app/src/main/res/drawable/background_gray.xml
  app/src/main/res/drawable/background_profile_container.xml
  app/src/main/res/drawable/ic_profile_repo.xml
  app/src/main/res/drawable/ic_profile_starred.xml
  app/src/main/res/drawable/ic_servicename_profile.xml
  app/src/main/res/drawable/ic_system_uicons_link.xml
  app/src/main/res/drawable/ic_system_uicons_location.xml
  app/src/main/res/drawable/ic_system_uicons_mail.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_userandprojectname.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature🔥, 진연주🍿, 박해민🌹

#49 홈화면 hilt 적용 #24
  app/src/main/java/com/example/reposearchapp/data/remote/GitApiService.kt
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/repository/issue/IssuePagingSource.kt
  app/src/main/java/com/example/reposearchapp/data/repository/issue/IssueRepository.kt
  app/src/main/java/com/example/reposearchapp/data/repository/notification/NotificationPagingSource.kt
  app/src/main/java/com/example/reposearchapp/data/repository/notification/NotificationRepository.kt
  app/src/main/java/com/example/reposearchapp/di/DataModule.kt
  app/src/main/java/com/example/reposearchapp/di/ProvideAPI.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/issue/IssueFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/issue/IssueViewModel.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationViewModel.kt
Labels: enhancement, Review Request🔥🔥

#53 서치 화면 progress bar 추가 #52
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: feature🔥

#54 불필요한 코드 제거, 리팩토링
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/repository/ProfileRepository.kt
  app/src/main/java/com/example/reposearchapp/presentation/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: refactor🛠

#55 홈 화면 추가 구현 사항
  app/src/main/java/com/example/reposearchapp/data/remote/GithubApi.kt
  app/src/main/java/com/example/reposearchapp/data/repository/issue/IssueRepository.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/issue/IssueOptionAdapter.kt
  app/src/main/java/com/example/reposearchapp/presentation/adapter/notification/NotificationViewHolder.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/issue/IssueFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/home/notification/NotificationFragment.kt
  app/src/main/java/com/example/reposearchapp/presentation/profile/ProfileFragment.kt
  app/src/main/java/com/example/reposearchapp/util/BindingAdapters.kt
  app/src/main/java/com/example/reposearchapp/util/IntExtension.kt
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/header_issue_option.xml
  app/src/main/res/layout/item_repo.xml
  app/src/main/res/xml/anim_spinner_click.xml
Labels: 진연주🍿, 박해민🌹, Review Request🔥🔥

#57 location 필드 nullable로 수정 #56
  app/src/main/java/com/example/reposearchapp/data/entity/UserResponse.kt
  app/src/main/java/com/example/reposearchapp/model/profile/UserModel.kt
Labels: bug🐞
